// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/wechatApp/wechatApp.proto

package WeChatService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for WechatApp service

func NewWechatAppEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for WechatApp service

type WechatAppService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (WechatApp_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (WechatApp_PingPongService, error)
}

type wechatAppService struct {
	c    client.Client
	name string
}

func NewWechatAppService(name string, c client.Client) WechatAppService {
	return &wechatAppService{
		c:    c,
		name: name,
	}
}

func (c *wechatAppService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "WechatApp.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wechatAppService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (WechatApp_StreamService, error) {
	req := c.c.NewRequest(c.name, "WechatApp.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &wechatAppServiceStream{stream}, nil
}

type WechatApp_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type wechatAppServiceStream struct {
	stream client.Stream
}

func (x *wechatAppServiceStream) Close() error {
	return x.stream.Close()
}

func (x *wechatAppServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *wechatAppServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *wechatAppServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *wechatAppServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *wechatAppService) PingPong(ctx context.Context, opts ...client.CallOption) (WechatApp_PingPongService, error) {
	req := c.c.NewRequest(c.name, "WechatApp.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &wechatAppServicePingPong{stream}, nil
}

type WechatApp_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type wechatAppServicePingPong struct {
	stream client.Stream
}

func (x *wechatAppServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *wechatAppServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *wechatAppServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *wechatAppServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *wechatAppServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *wechatAppServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for WechatApp service

type WechatAppHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, WechatApp_StreamStream) error
	PingPong(context.Context, WechatApp_PingPongStream) error
}

func RegisterWechatAppHandler(s server.Server, hdlr WechatAppHandler, opts ...server.HandlerOption) error {
	type wechatApp interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type WechatApp struct {
		wechatApp
	}
	h := &wechatAppHandler{hdlr}
	return s.Handle(s.NewHandler(&WechatApp{h}, opts...))
}

type wechatAppHandler struct {
	WechatAppHandler
}

func (h *wechatAppHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.WechatAppHandler.Call(ctx, in, out)
}

func (h *wechatAppHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.WechatAppHandler.Stream(ctx, m, &wechatAppStreamStream{stream})
}

type WechatApp_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type wechatAppStreamStream struct {
	stream server.Stream
}

func (x *wechatAppStreamStream) Close() error {
	return x.stream.Close()
}

func (x *wechatAppStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *wechatAppStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *wechatAppStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *wechatAppStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *wechatAppHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.WechatAppHandler.PingPong(ctx, &wechatAppPingPongStream{stream})
}

type WechatApp_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type wechatAppPingPongStream struct {
	stream server.Stream
}

func (x *wechatAppPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *wechatAppPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *wechatAppPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *wechatAppPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *wechatAppPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *wechatAppPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
